//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCrud2.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrdersModelCodeFirstResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrdersModelCodeFirstResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCrud2.Localization.OrdersModelCodeFirstResources", typeof(OrdersModelCodeFirstResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Company Name.
        /// </summary>
        public static string Customer_CompanyName {
            get {
                return ResourceManager.GetString("Customer_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer Code.
        /// </summary>
        public static string Customer_CustomerCode {
            get {
                return ResourceManager.GetString("Customer_CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        public static string Customer_Id {
            get {
                return ResourceManager.GetString("Customer_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Person Name.
        /// </summary>
        public static string Customer_PersonName {
            get {
                return ResourceManager.GetString("Customer_PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer.
        /// </summary>
        public static string CustomerPlural {
            get {
                return ResourceManager.GetString("CustomerPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer.
        /// </summary>
        public static string Order_Customer {
            get {
                return ResourceManager.GetString("Order_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        public static string Order_Id {
            get {
                return ResourceManager.GetString("Order_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order Date.
        /// </summary>
        public static string Order_OrderDate {
            get {
                return ResourceManager.GetString("Order_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order Subject.
        /// </summary>
        public static string Order_OrderSubject {
            get {
                return ResourceManager.GetString("Order_OrderSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sum Price B.
        /// </summary>
        public static string Order_SumPriceB {
            get {
                return ResourceManager.GetString("Order_SumPriceB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sum Price N.
        /// </summary>
        public static string Order_SumPriceN {
            get {
                return ResourceManager.GetString("Order_SumPriceN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order Item.
        /// </summary>
        public static string OrderItem {
            get {
                return ResourceManager.GetString("OrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count VAT.
        /// </summary>
        public static string OrderItem_CountVAT {
            get {
                return ResourceManager.GetString("OrderItem_CountVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        public static string OrderItem_Id {
            get {
                return ResourceManager.GetString("OrderItem_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order.
        /// </summary>
        public static string OrderItem_Order {
            get {
                return ResourceManager.GetString("OrderItem_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product.
        /// </summary>
        public static string OrderItem_Product {
            get {
                return ResourceManager.GetString("OrderItem_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity.
        /// </summary>
        public static string OrderItem_Quantity {
            get {
                return ResourceManager.GetString("OrderItem_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unit Price B.
        /// </summary>
        public static string OrderItem_UnitPriceB {
            get {
                return ResourceManager.GetString("OrderItem_UnitPriceB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order Item.
        /// </summary>
        public static string OrderItemPlural {
            get {
                return ResourceManager.GetString("OrderItemPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order.
        /// </summary>
        public static string OrderPlural {
            get {
                return ResourceManager.GetString("OrderPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        public static string Product_Id {
            get {
                return ResourceManager.GetString("Product_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product Code.
        /// </summary>
        public static string Product_ProductCode {
            get {
                return ResourceManager.GetString("Product_ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product Name.
        /// </summary>
        public static string Product_ProductName {
            get {
                return ResourceManager.GetString("Product_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unit Price N.
        /// </summary>
        public static string Product_UnitPriceN {
            get {
                return ResourceManager.GetString("Product_UnitPriceN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product.
        /// </summary>
        public static string ProductPlural {
            get {
                return ResourceManager.GetString("ProductPlural", resourceCulture);
            }
        }
    }
}
